version = 1

[root]
level = "DEBUG"
handlers = [ "console", "file"]

[formatters.file]
class = "logging.Formatter"
format = "[%(asctime)s][%(name)s]:[%(levelname)s] %(message)s"
datefmt = "%Y-%m-%d %H-%M-%S"

[formatters.client]
class = "logging.Formatter"
format = "[%(asctime)s][%(name)s]:[%(levelname)s] %(message)s"
datefmt = "%Y-%m-%d %H-%M-%S"

[formatters.server]
class = "logging.Formatter"
format = "[%(asctime)s][%(name)s]:[%(levelname)s] %(message)s"
datefmt = "%Y-%m-%d %H-%M-%S"

[handlers.console]
class = "logging.StreamHandler"
formatter = "file"
level = "DEBUG"

[handlers.file]
class = "logging.FileHandler"
filename = "{} DR.log"
datefmt = "%Y-%m-%d %H-%M-%S"
encoding = "utf-8"
formatter = "file"
level = "DEBUG"
mode = "w"

[loggers.client]
level = "DEBUG"
handlers = []

[loggers.server]
level = "DEBUG"
handlers = []

[loggers.main]
level = "DEBUG"
handlers = []