[runtime]
fps = 60
version = "0.6.5.0"
language = "zh-CN"
date_fmt = "%Y-%m-%d %H-%M-%S"
write_py_v = "3.8.10"
fonts_folder = "libs/fonts"

[window]
style = "None"
width = 1173
height = 692
visible = true
gui_scale = 1
caption = "Difficult Rocket v{DR_version}|DR_rs v{DR_Rust_get_version}"
resizable = true
full_screen = false

[window.default]
width = 1024
height = 768
gui_scale = 1
